### PR TITLE
101-Styling | Added tests for alternate style tags

### PR DESCRIPTION
**Pull request by vincent-gros**
Tests for day and night values.
@mgylling, is it ok for you?

(See #62)

### CODE REVIEW

**Comment by danielweck** [comment]
I would suggest adding the `alternate` value to the `link@rel` attribute for the `link@class="night"` stylesheet, so that the `link@class="day"` CSS becomes the "preferred" reading system option.

**Comment by danielweck** [comment]
PS to the above comment:
http://www.idpf.org/epub/altss-tags/#style-sets
(not implemented yet in Readium, FYi)

**Comment by danielweck** [comment]
Suggested change:

```
<!-- see http://www.idpf.org/epub/altss-tags/#style-sets -->

<!-- two persistent style sheets (no title attribute) -->
<link rel="stylesheet" type="text/css" href="../css/base.css" />
<link rel="stylesheet" type="text/css" href="../css/styling.css" />

<!-- two alternate style sheets (with different title attributes), the first being preferred as it does not have  alternate value in the rel attribute -->
<link rel="stylesheet" type="text/css" href="../css/day.css" class="day" title="day" />
<link rel="stylesheet alternate" type="text/css" href="../css/night.css" class="night" title="night" />
```

**Comment by mgylling** [comment]
LGTM

**Comment by mgylling** [comment]
...and thanks @vincent-gros !

**Pull request merged**
